set -g mouse on 
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Navigation(Same as my zsh shell for history and navigation in commands that replaces arrow key)
# Navigate to the upper pane with Ctrl+b then Ctrl+p
bind ^p select-pane -U

# Navigate to the lower pane with Ctrl+b then Ctrl+n
bind ^n select-pane -D

# Navigate to the left pane with Ctrl+b then Ctrl+a
bind ^a select-pane -L

# Navigate to the right pane with Ctrl+b then Ctrl+e
bind ^e select-pane -R
